<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Folio.Ingestion/Folio.Ingestion.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="StackExchange.Redis" />
        <PackageReference Include="Testcontainers.Redis" />

    </ItemGroup>

</Project>
